version: "3.9"
services:
  mongo:
    image: mongo:3.6
    command: --nojournal
  orion:
      image: fiware/orion-ld
      links:
        - mongo
      ports:
        - "1026:1026"
      command: -dbhost mongo -lmtmp