CREATE_SEQUENCE_METADATA = """
CREATE SEQUENCE METADATA_IDENTITY
     START WITH 1
     INCREMENT BY 1
     NOCACHE
     NOCYCLE
"""

CREATE_TABLE_METADATA = """CREATE TABLE Metadata (
    id NUMBER NOT NULL,
    time_of_event TIMESTAMP NOT NULL,
    in_out VARCHAR2(10) NOT NULL,
    car_body_id VARCHAR2(20) NOT NULL,
    car_body_type VARCHAR2(10) NOT NULL,
    voltage_program_type VARCHAR2(10) NOT NULL,
    skid_id NUMBER NOT NULL,
    pendulum_id NUMBER NOT NULL,
    CONSTRAINT metadata_pk PRIMARY KEY (id)
)"""

METADATA_TRIGGER = """
CREATE TRIGGER METADATA_TRIGGER
BEFORE INSERT ON Metadata
FOR EACH ROW
BEGIN
   :NEW.id := METADATA_IDENTITY.NextVal;
END;
"""

CREATE_SEQUENCE_SMT = """
CREATE SEQUENCE SMT_IDENTITY
     START WITH 1
     INCREMENT BY 1
     NOCACHE
     NOCYCLE
"""

CREATE_TABLE_SMT = """CREATE TABLE SMT (
    id NUMBER NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    skid_id NUMBER NOT NULL,
    type_of_smt_event VARCHAR2(10) NOT NULL,
    CONSTRAINT smt_id PRIMARY KEY (id)
)"""

SMT_TRIGGER = """
CREATE TRIGGER SMT_TRIGGER
BEFORE INSERT ON SMT
FOR EACH ROW
BEGIN
   :NEW.id := SMT_IDENTITY.NextVal;
END;
"""